// <auto-generated />
using System;
using FamilyTree.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FamilyTree.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260413134810_AddWorldPermissions")]
    partial class AddWorldPermissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FamilyTree.Domain.Entities.Entity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Biography")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("BirthPlace")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DeathDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MaidenName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("Parent1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Parent2Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Residence")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Species")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Parent1Id");

                    b.HasIndex("Parent2Id");

                    b.HasIndex("Type");

                    b.HasIndex("WorldId");

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("FamilyTree.Domain.Entities.EntityFamilyTree", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FamilyTreeId")
                        .HasColumnType("uuid");

                    b.Property<double?>("PositionX")
                        .HasColumnType("double precision");

                    b.Property<double?>("PositionY")
                        .HasColumnType("double precision");

                    b.HasKey("EntityId", "FamilyTreeId");

                    b.HasIndex("EntityId");

                    b.HasIndex("FamilyTreeId");

                    b.ToTable("EntityFamilyTrees");
                });

            modelBuilder.Entity("FamilyTree.Domain.Entities.FamilyTree", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Name");

                    b.HasIndex("WorldId");

                    b.ToTable("FamilyTrees");
                });

            modelBuilder.Entity("FamilyTree.Domain.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("WorldId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("FamilyTree.Domain.Entities.Relationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("Entity1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Entity2Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Entity1Id");

                    b.HasIndex("Entity2Id");

                    b.HasIndex("RelationshipType");

                    b.ToTable("Relationships");
                });

            modelBuilder.Entity("FamilyTree.Domain.Entities.TreePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PermissionLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TreeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TreeId");

                    b.HasIndex("UserId");

                    b.HasIndex("TreeId", "UserId")
                        .IsUnique();

                    b.ToTable("TreePermissions");
                });

            modelBuilder.Entity("FamilyTree.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FamilyTree.Domain.Entities.World", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Name");

                    b.ToTable("Worlds");
                });

            modelBuilder.Entity("FamilyTree.Domain.Entities.WorldPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanEdit")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorldId", "UserId")
                        .IsUnique();

                    b.ToTable("WorldPermissions");
                });

            modelBuilder.Entity("FamilyTree.Domain.Entities.Entity", b =>
                {
                    b.HasOne("FamilyTree.Domain.Entities.Entity", "Parent1")
                        .WithMany("ChildrenAsParent1")
                        .HasForeignKey("Parent1Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FamilyTree.Domain.Entities.Entity", "Parent2")
                        .WithMany("ChildrenAsParent2")
                        .HasForeignKey("Parent2Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FamilyTree.Domain.Entities.World", "World")
                        .WithMany("Entities")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent1");

                    b.Navigation("Parent2");

                    b.Navigation("World");
                });

            modelBuilder.Entity("FamilyTree.Domain.Entities.EntityFamilyTree", b =>
                {
                    b.HasOne("FamilyTree.Domain.Entities.Entity", "Entity")
                        .WithMany("EntityFamilyTrees")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyTree.Domain.Entities.FamilyTree", "FamilyTree")
                        .WithMany("EntityFamilyTrees")
                        .HasForeignKey("FamilyTreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("FamilyTree");
                });

            modelBuilder.Entity("FamilyTree.Domain.Entities.FamilyTree", b =>
                {
                    b.HasOne("FamilyTree.Domain.Entities.User", "Creator")
                        .WithMany("CreatedFamilyTrees")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FamilyTree.Domain.Entities.World", "World")
                        .WithMany("FamilyTrees")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("World");
                });

            modelBuilder.Entity("FamilyTree.Domain.Entities.Note", b =>
                {
                    b.HasOne("FamilyTree.Domain.Entities.Entity", "Entity")
                        .WithMany("Notes")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FamilyTree.Domain.Entities.World", "World")
                        .WithMany("Notes")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Entity");

                    b.Navigation("World");
                });

            modelBuilder.Entity("FamilyTree.Domain.Entities.Relationship", b =>
                {
                    b.HasOne("FamilyTree.Domain.Entities.Entity", "Entity1")
                        .WithMany("RelationshipsAsEntity1")
                        .HasForeignKey("Entity1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyTree.Domain.Entities.Entity", "Entity2")
                        .WithMany("RelationshipsAsEntity2")
                        .HasForeignKey("Entity2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entity1");

                    b.Navigation("Entity2");
                });

            modelBuilder.Entity("FamilyTree.Domain.Entities.TreePermission", b =>
                {
                    b.HasOne("FamilyTree.Domain.Entities.FamilyTree", "Tree")
                        .WithMany()
                        .HasForeignKey("TreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyTree.Domain.Entities.User", "User")
                        .WithMany("TreePermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tree");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FamilyTree.Domain.Entities.World", b =>
                {
                    b.HasOne("FamilyTree.Domain.Entities.User", "CreatedBy")
                        .WithMany("CreatedWorlds")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("FamilyTree.Domain.Entities.WorldPermission", b =>
                {
                    b.HasOne("FamilyTree.Domain.Entities.User", "User")
                        .WithMany("WorldPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyTree.Domain.Entities.World", "World")
                        .WithMany("Permissions")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("World");
                });

            modelBuilder.Entity("FamilyTree.Domain.Entities.Entity", b =>
                {
                    b.Navigation("ChildrenAsParent1");

                    b.Navigation("ChildrenAsParent2");

                    b.Navigation("EntityFamilyTrees");

                    b.Navigation("Notes");

                    b.Navigation("RelationshipsAsEntity1");

                    b.Navigation("RelationshipsAsEntity2");
                });

            modelBuilder.Entity("FamilyTree.Domain.Entities.FamilyTree", b =>
                {
                    b.Navigation("EntityFamilyTrees");
                });

            modelBuilder.Entity("FamilyTree.Domain.Entities.User", b =>
                {
                    b.Navigation("CreatedFamilyTrees");

                    b.Navigation("CreatedWorlds");

                    b.Navigation("TreePermissions");

                    b.Navigation("WorldPermissions");
                });

            modelBuilder.Entity("FamilyTree.Domain.Entities.World", b =>
                {
                    b.Navigation("Entities");

                    b.Navigation("FamilyTrees");

                    b.Navigation("Notes");

                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
