// <auto-generated />
using System;
using Veilora.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Veilora.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260415130000_RemovePlaceEntities")]
    partial class RemovePlaceEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Veilora.Domain.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Biography")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("BirthDateSuffix")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("BirthPlaceLocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DeathDate")
                        .HasColumnType("date");

                    b.Property<string>("DeathDateSuffix")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("DeathPlaceLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("HairColour")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Height")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MaidenName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OtherNames")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("Parent1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Parent2Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Position")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Residence")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Species")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BirthPlaceLocationId");

                    b.HasIndex("DeathPlaceLocationId");

                    b.HasIndex("Name");

                    b.HasIndex("Parent1Id");

                    b.HasIndex("Parent2Id");

                    b.HasIndex("WorldId");

                    b.ToTable("Characters", (string)null);
                });

            modelBuilder.Entity("Veilora.Domain.Entities.CharacterFamilyTree", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FamilyTreeId")
                        .HasColumnType("uuid");

                    b.Property<double?>("PositionX")
                        .HasColumnType("double precision");

                    b.Property<double?>("PositionY")
                        .HasColumnType("double precision");

                    b.HasKey("CharacterId", "FamilyTreeId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("FamilyTreeId");

                    b.ToTable("CharacterFamilyTrees", (string)null);
                });

            modelBuilder.Entity("Veilora.Domain.Entities.CharacterLocation", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.HasKey("CharacterId", "LocationId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("LocationId");

                    b.ToTable("CharacterLocations");
                });

            modelBuilder.Entity("Veilora.Domain.Entities.Entity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Type");

                    b.HasIndex("WorldId");

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("Veilora.Domain.Entities.EntityAffiliation", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.HasKey("CharacterId", "GroupId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("GroupId");

                    b.ToTable("EntityAffiliations");
                });

            modelBuilder.Entity("Veilora.Domain.Entities.EntityLanguage", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.HasKey("CharacterId", "LanguageId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("LanguageId");

                    b.ToTable("EntityLanguages");
                });

            modelBuilder.Entity("Veilora.Domain.Entities.FamilyTree", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Name");

                    b.HasIndex("WorldId");

                    b.ToTable("FamilyTrees");
                });

            modelBuilder.Entity("Veilora.Domain.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorldId");

                    b.HasIndex("WorldId", "Name")
                        .IsUnique();

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Veilora.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorldId");

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("Veilora.Domain.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("WorldId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Veilora.Domain.Entities.Relationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Character1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Character2Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Character1Id");

                    b.HasIndex("Character2Id");

                    b.HasIndex("RelationshipType");

                    b.ToTable("Relationships");
                });

            modelBuilder.Entity("Veilora.Domain.Entities.TreePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PermissionLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TreeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TreeId");

                    b.HasIndex("UserId");

                    b.HasIndex("TreeId", "UserId")
                        .IsUnique();

                    b.ToTable("TreePermissions");
                });

            modelBuilder.Entity("Veilora.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Veilora.Domain.Entities.World", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Name");

                    b.ToTable("Worlds");
                });

            modelBuilder.Entity("Veilora.Domain.Entities.WorldPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanEdit")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorldId", "UserId")
                        .IsUnique();

                    b.ToTable("WorldPermissions");
                });

            modelBuilder.Entity("Veilora.Domain.Entities.Character", b =>
                {
                    b.HasOne("Veilora.Domain.Entities.Location", "BirthPlaceLocation")
                        .WithMany()
                        .HasForeignKey("BirthPlaceLocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Veilora.Domain.Entities.Location", "DeathPlaceLocation")
                        .WithMany()
                        .HasForeignKey("DeathPlaceLocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Veilora.Domain.Entities.Character", "Parent1")
                        .WithMany("ChildrenAsParent1")
                        .HasForeignKey("Parent1Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Veilora.Domain.Entities.Character", "Parent2")
                        .WithMany("ChildrenAsParent2")
                        .HasForeignKey("Parent2Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Veilora.Domain.Entities.World", "World")
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BirthPlaceLocation");

                    b.Navigation("DeathPlaceLocation");

                    b.Navigation("Parent1");

                    b.Navigation("Parent2");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Veilora.Domain.Entities.CharacterFamilyTree", b =>
                {
                    b.HasOne("Veilora.Domain.Entities.Character", "Character")
                        .WithMany("CharacterFamilyTrees")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Veilora.Domain.Entities.FamilyTree", "FamilyTree")
                        .WithMany("CharacterFamilyTrees")
                        .HasForeignKey("FamilyTreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("FamilyTree");
                });

            modelBuilder.Entity("Veilora.Domain.Entities.CharacterLocation", b =>
                {
                    b.HasOne("Veilora.Domain.Entities.Character", "Character")
                        .WithMany("Locations")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Veilora.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Veilora.Domain.Entities.Entity", b =>
                {
                    b.HasOne("Veilora.Domain.Entities.World", "World")
                        .WithMany("Entities")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("Veilora.Domain.Entities.EntityAffiliation", b =>
                {
                    b.HasOne("Veilora.Domain.Entities.Character", "Character")
                        .WithMany("Affiliations")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Veilora.Domain.Entities.Entity", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Veilora.Domain.Entities.EntityLanguage", b =>
                {
                    b.HasOne("Veilora.Domain.Entities.Character", "Character")
                        .WithMany("Languages")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Veilora.Domain.Entities.Language", "Language")
                        .WithMany("EntityLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Veilora.Domain.Entities.FamilyTree", b =>
                {
                    b.HasOne("Veilora.Domain.Entities.User", "Creator")
                        .WithMany("CreatedFamilyTrees")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Veilora.Domain.Entities.World", "World")
                        .WithMany("FamilyTrees")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Veilora.Domain.Entities.Language", b =>
                {
                    b.HasOne("Veilora.Domain.Entities.World", "World")
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("Veilora.Domain.Entities.Location", b =>
                {
                    b.HasOne("Veilora.Domain.Entities.World", "World")
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("Veilora.Domain.Entities.Note", b =>
                {
                    b.HasOne("Veilora.Domain.Entities.Entity", "Entity")
                        .WithMany("Notes")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Veilora.Domain.Entities.World", "World")
                        .WithMany("Notes")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Entity");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Veilora.Domain.Entities.Relationship", b =>
                {
                    b.HasOne("Veilora.Domain.Entities.Character", "Character1")
                        .WithMany("RelationshipsAsCharacter1")
                        .HasForeignKey("Character1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Veilora.Domain.Entities.Character", "Character2")
                        .WithMany("RelationshipsAsCharacter2")
                        .HasForeignKey("Character2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character1");

                    b.Navigation("Character2");
                });

            modelBuilder.Entity("Veilora.Domain.Entities.TreePermission", b =>
                {
                    b.HasOne("Veilora.Domain.Entities.FamilyTree", "Tree")
                        .WithMany()
                        .HasForeignKey("TreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Veilora.Domain.Entities.User", "User")
                        .WithMany("TreePermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tree");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Veilora.Domain.Entities.World", b =>
                {
                    b.HasOne("Veilora.Domain.Entities.User", "CreatedBy")
                        .WithMany("CreatedWorlds")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Veilora.Domain.Entities.WorldPermission", b =>
                {
                    b.HasOne("Veilora.Domain.Entities.User", "User")
                        .WithMany("WorldPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Veilora.Domain.Entities.World", "World")
                        .WithMany("Permissions")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Veilora.Domain.Entities.Character", b =>
                {
                    b.Navigation("Affiliations");

                    b.Navigation("CharacterFamilyTrees");

                    b.Navigation("ChildrenAsParent1");

                    b.Navigation("ChildrenAsParent2");

                    b.Navigation("Languages");

                    b.Navigation("Locations");

                    b.Navigation("RelationshipsAsCharacter1");

                    b.Navigation("RelationshipsAsCharacter2");
                });

            modelBuilder.Entity("Veilora.Domain.Entities.Entity", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("Veilora.Domain.Entities.FamilyTree", b =>
                {
                    b.Navigation("CharacterFamilyTrees");
                });

            modelBuilder.Entity("Veilora.Domain.Entities.Language", b =>
                {
                    b.Navigation("EntityLanguages");
                });

            modelBuilder.Entity("Veilora.Domain.Entities.User", b =>
                {
                    b.Navigation("CreatedFamilyTrees");

                    b.Navigation("CreatedWorlds");

                    b.Navigation("TreePermissions");

                    b.Navigation("WorldPermissions");
                });

            modelBuilder.Entity("Veilora.Domain.Entities.World", b =>
                {
                    b.Navigation("Entities");

                    b.Navigation("FamilyTrees");

                    b.Navigation("Notes");

                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
