import type { EntityRefDto } from './entityRef';
import type { LanguageDto } from './language';

export type Gender = 'Male' | 'Female' | 'Other' | 'Unknown';

export interface CharacterDto {
  id: string;
  name: string;
  worldId: string;
  description?: string;
  firstName?: string;
  lastName?: string;
  middleName?: string;
  maidenName?: string;
  species?: string;
  gender?: Gender;
  birthDate?: string;
  birthDateSuffix?: string;
  deathDate?: string;
  deathDateSuffix?: string;
  birthPlaceEntityId?: string;
  birthPlaceEntityName?: string;
  deathPlaceEntityId?: string;
  deathPlaceEntityName?: string;
  residence?: string;
  biography?: string;
  profilePhotoUrl?: string;
  otherNames?: string;
  position?: string;
  height?: string;
  hairColour?: string;
  parent1Id?: string;
  parent2Id?: string;
  locations: EntityRefDto[];
  affiliations: EntityRefDto[];
  languages: LanguageDto[];
  spouses: EntityRefDto[];
  children: EntityRefDto[];
  createdAt: string;
  updatedAt: string;
}

export interface CreateCharacterDto {
  name: string;
  worldId: string;
  description?: string;
  firstName?: string;
  lastName?: string;
  middleName?: string;
  maidenName?: string;
  species?: string;
  gender?: Gender;
  birthDate?: string;
  birthDateSuffix?: string;
  deathDate?: string;
  deathDateSuffix?: string;
  birthPlaceEntityId?: string;
  birthPlaceName?: string;
  deathPlaceEntityId?: string;
  deathPlaceName?: string;
  residence?: string;
  biography?: string;
  otherNames?: string;
  position?: string;
  height?: string;
  hairColour?: string;
  parent1Id?: string;
  parent2Id?: string;
  locationIds?: string[];
  locationNames?: string[];
  affiliationIds?: string[];
  affiliationNames?: string[];
  languageIds?: string[];
  spouseIds?: string[];
  childIds?: string[];
}

export interface UpdateCharacterDto {
  name: string;
  description?: string;
  firstName?: string;
  lastName?: string;
  middleName?: string;
  maidenName?: string;
  species?: string;
  gender?: Gender;
  birthDate?: string;
  birthDateSuffix?: string;
  deathDate?: string;
  deathDateSuffix?: string;
  birthPlaceEntityId?: string | null;
  birthPlaceName?: string;
  deathPlaceEntityId?: string | null;
  deathPlaceName?: string;
  residence?: string;
  biography?: string;
  profilePhotoUrl?: string;
  otherNames?: string;
  position?: string;
  height?: string;
  hairColour?: string;
  parent1Id?: string | null;
  parent2Id?: string | null;
  locationIds: string[];
  locationNames?: string[];
  affiliationIds: string[];
  affiliationNames?: string[];
  languageIds: string[];
  spouseIds: string[];
  childIds: string[];
}
